<?php

/**
 * @file
 *   Integrates Userpoints with Facebook-style Statuses.
 */

/**
 * Implements hook_userpoints().
 */
function fbss_userpoints_userpoints($op, $params = array()) {
  if ($op == 'setting') {
    $form['facebook_status'] = array(
      '#type' => 'fieldset',
      '#title' => t('Facebook-style Statuses'),
      '#collapsible' => TRUE,
      '#collapsed' => TRUE,
    );
    $form['facebook_status']['facebook_status_userpoints_own'] = array(
      '#type' => 'textfield',
      '#title' => t("Userpoints for changing one's own status"),
      '#default_value' => variable_get('facebook_status_userpoints_own', 0),
    );
    $form['facebook_status']['facebook_status_userpoints_other'] = array(
      '#type' => 'textfield',
      '#title' => t("Userpoints for posting a status message to another entity"),
      '#default_value' => variable_get('facebook_status_userpoints_other', 0),
    );
    $form['facebook_status']['facebook_status_userpoints_max'] = array(
      '#type' => 'textfield',
      '#title' => t('Maximum number of Userpoints from posting statuses per day'),
      '#description' => t('Set to zero for no limit.') . ' ' .
        t('Note that the actual number of points awarded per day could be higher than this if this value is not a multiple of the points given above.'),
      '#default_value' => variable_get('facebook_status_userpoints_max', 5),
    );
    $form['#validate'][] = '_fbss_userpoints_validate';
    return $form;
  }
}

/**
 * Validate function for the Userpoints settings.
 */
function _fbss_userpoints_validate($form, &$form_state) {
  $v = $form_state['values'];
  if (!is_numeric($v['facebook_status_userpoints_own']) || $v['facebook_status_userpoints_own'] < 0) {
    form_set_error('facebook_status_userpoints_own', t("Userpoints for changing one's own status must be a non-negative integer."));
  }
  if (!is_numeric($v['facebook_status_userpoints_other']) || $v['facebook_status_userpoints_other'] < 0) {
    form_set_error('facebook_status_userpoints_other', t("Userpoints for posting a message on another user's profile must be a non-negative integer."));
  }
  if (!is_numeric($v['facebook_status_userpoints_max']) || $v['facebook_status_userpoints_max'] < 0) {
    form_set_error('facebook_status_userpoints_max', t('The maximum number of Userpoints from posting statuses per day must be a non-negative integer.'));
  }
}

/**
 * Implements hook_facebook_status_save().
 */
function fbss_userpoints_facebook_status_save($status, $context, $edit) {
  $sender = _facebook_status_user_load($status->sender);
  $recipient = $context['handler']->load_recipient($status->recipient);
  $points_today = db_query("SELECT SUM(points) FROM {userpoints_txn}
    WHERE uid = :uid AND time_stamp > :time_stamp
      AND (operation = :(operation OR operation = :operation)
      AND expired = :expired AND status = :status", array(':uid' => $sender->uid, ':time_stamp' => REQUEST_TIME - 86400, ':(operation' => 'facebook_status add own', ':operation' => 'facebook_status add other', ':expired' => 0, ':status' => 0))->fetchField();
  if (variable_get('facebook_status_userpoints_max', 5) && $points_today > variable_get('facebook_status_userpoints_max', 5)) {
    return;
  }
  $params = array(
    'uid' => $sender->uid,
    'reference' => $sid,
    // Unknown purpose.
    //'entity_id' => $sid,
    //'entity_type' => 'facebook_status',
  );
  if ($status->sender == $status->recipient && $status->type == 'user') {
    $params['description'] = t('!user posted a new status.', array('!user' => theme('username', array('account' => $sender))));
    $params['points'] = variable_get('facebook_status_userpoints_own', 0);
    $params['operation'] = 'facebook_status add own';
  }
  elseif ($status->type == 'user') {
    $params['description'] = t('!sender wrote a message to !recipient',
      array('!sender' => theme('username', array('account' => $sender)), '!recipient' => $context['handler']->recipient_link($recipient)));
    $params['points'] = variable_get('facebook_status_userpoints_other', 0);
    $params['operation'] = 'facebook_status add other';
  }
  else {
    $params['description'] = t('!sender wrote a message at !recipient',
      array('!sender' => theme('username', array('account' => $sender)), '!recipient' => $context['handler']->recipient_link($recipient)));
    $params['points'] = variable_get('facebook_status_userpoints_other', 0);
    $params['operation'] = 'facebook_status add other';
  }
  userpoints_userpointsapi($params);
}

/**
 * Implements hook_facebook_status_delete().
 */
function fbss_userpoints_facebook_status_delete($sid) {
  $status = facebook_status_load($sid);
  $sender = _facebook_status_user_load(array('uid' => $status->sender));
  global $user;
  $result = db_fetch_object(db_query("SELECT points FROM {userpoints_txn} WHERE operation LIKE 'facebook_status add%%' AND reference = :reference AND uid = :uid", array(':reference' => $sid, ':uid' => $sender->uid)));
  $params = array(
    'uid' => $sender->uid,
    'points' => 0 - $result->points,
    'operation' => 'facebook_status delete',
  );
  if ($user->uid == $sender->uid) {
    $params['description'] = t('!user deleted a status message.', array('!user' => theme('username', array('account' => $user))));
  }
  else {
    $params['description'] = t('!user deleted a message by !sender',
      array('!user' => theme('username', array('account' => $user)), '!sender' => theme('username', array('account' => $sender))));
  }
  userpoints_userpointsapi($params);
}
