<?php

/**
 * @file
 *   Integrates Flag with Facebook-style Statuses.
 */

/**
 * Implements hook_facebook_status_delete().
 */
function fbss_flag_facebook_status_delete($sid) {
  // TODO Please review the conversion of this statement to the D7 database API syntax.
  /* db_query("DELETE FROM {flag_content} WHERE content_type = 'facebook_status' AND content_id = %d", $sid) */
  db_delete('flag_content')
  ->condition('content_type', 'facebook_status')
  ->condition('content_id', $sid)
  ->execute();
  // TODO Please review the conversion of this statement to the D7 database API syntax.
  /* db_query("DELETE FROM {flag_counts} WHERE content_type = 'facebook_status' AND content_id = %d", $sid) */
  db_delete('flag_counts')
  ->condition('content_type', 'facebook_status')
  ->condition('content_id', $sid)
  ->execute();
}

/**
 * Implements hook_flag_definitions().
 */
function fbss_flag_flag_definitions() {
  return array(
    'facebook_status' => array(
      'title' => 'Facebook-style Statuses',
      'description' => t('Statuses are short textual messages users use to express themselves.'),
      'handler' => 'fbss_flag',
    ),
  );
}

/**
 * Implements hook_flag_default_flags().
 */
function fbss_flag_flag_default_flags() {
  $flags = array();
  $flags[] = array(
    'content_type' => 'facebook_status',
    'name' => 'like',
    'title' => t('Like'),
    'roles' => array('2'),
    'global' => FALSE,
    'types' => array('page'),
    'flag_short' => t('Like'),
    'flag_long' => '',
    'flag_message' => '',
    'unflag_short' => t('Un-like'),
    'unflag_long' => '',
    'unflag_message' => '',
    'show_on_page' => FALSE,
    'show_on_teaser' => FALSE,
    'show_on_form' => FALSE,
    'status' => TRUE,
    'locked' => array('name', 'global', 'types', 'show_on_page', 'show_on_teaser', 'show_on_form', 'status'),
  );
  $flags[] = array(
    'content_type' => 'user',
    'name' => 'follow',
    'title' => t('Follow'),
    'roles' => array('2'),
    'global' => FALSE,
    'types' => array('-'),
    'flag_short' => t('Follow'),
    'flag_long' => '',
    'flag_message' => t('Following'),
    'unflag_short' => t('Unfollow'),
    'unflag_long' => '',
    'unflag_message' => '',
    'show_on_page' => TRUE,
    'show_on_teaser' => FALSE,
    'show_on_form' => FALSE,
    'status' => FALSE,
    'locked' => array('name', 'global', 'types', 'show_on_teaser', 'show_on_form', 'status'),
  );
  return $flags;
}

//This is here because the Flag module does not support magic include files.
module_load_include('inc', 'fbss_flag', 'fbss_flag.flag');
