<?php

/**
 * @file
 *   Integrates Rules with Facebook-style Statuses.
 */

/**
 * Implements hook_facebook_status_delete().
 */
function fbss_rules_facebook_status_delete($sid) {
  rules_invoke_event('facebook_status_delete', facebook_status_load($sid));
}

/**
 * Implements hook_facebook_status_save().
 */
function fbss_rules_facebook_status_save($status, $context, $edit) {
  if ($edit) {
    rules_invoke_event('facebook_status_edit', $status, $context);
  }
  else {
    rules_invoke_event('facebook_status_save', $status, $context);
  }
}
